version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://peakmeshop.cdgyeqckwk3n.ap-northeast-2.rds.amazonaws.com:5432/peakmeshop
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=ghkwjd3ehd!
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - APP_JWT_SECRET=4t7w!z%C*F-JaNdRgUkXp2s5v8y/B?E(H+KbPeShVmYq3t6w9z$C&F)J@NcQfTjW
      - APP_JWT_EXPIRATION=3600000
      - APP_JWT_REFRESH_EXPIRATION=86400000
      - SERVER_PORT=80

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: